function makefood_season_tempfig(Ww_mat, seasonal_amp, foodDensity, muPlus, nmap)


for y = 1:length(seasonal_amp)
f1(y,:) = Ww_mat(:,1,y);
% f1s2 = Ww_mat(:,1,y);
% f1s3 = Ww_mat(:,1,y);
% f1s4 = Ww_mat(:,1,y);

f2(y,:) = Ww_mat(:,2,y);
% f2s2 = Ww_mat(:,2,y);
% f2s3 = Ww_mat(:,2,y);
% f2s4 = Ww_mat(:,2,y);

f3(y,:) = Ww_mat(:,3,y);
% f3s2 = Ww_mat(:,3,y);
% f3s3 = Ww_mat(:,3,y);
% f3s4 = Ww_mat(:,3,y);

end


fid1 = figure;
figure(fid1)
hold on

for x = 1:4
plot(1,f3(1,x), 'o', 'color', nmap(x,1:3), ...
        'MarkerFaceColor' , nmap(x,1:3), ...
        'MarkerSize', 8)
    plot(2,f3(4,x), 'o', 'color', nmap(x,1:3), ...
        'MarkerFaceColor' , nmap(x,1:3), ...
        'MarkerSize', 8)
end
xlim([0.5 2.5])
% ylim([0 100])
title(strcat('+', int2str(muPlus), ' samp=', int2str(seasonal_amp(y))));
setWwProperties


% figure
% plot(foodDensity, [f1(1,1) f2(1,1) f3(1,1)],'-o', ...
%         'color', nmap(1,1:3), ...
%         'LineWidth', 1, ...
%         'MarkerFaceColor' , nmap(1,1:3), ...
%         'MarkerSize', 10)
% 
%     figure
%     hold on
% % for y = 1:length(seasonal_amp)
%     for x = 1:4
%     plot(foodDensity(1),f1(1,x),'o', ...
%         'color', nmap(x,1:3), ...
%         'LineWidth', 2, ...
%         'MarkerFaceColor' , nmap(x,1:3), ...
%         'MarkerSize', 8)
%   	plot(foodDensity(1),f1(4,x),'o', ...
%         'color', nmap(x,1:3), ...
%         'LineWidth', 2,'MarkerSize', 8)
% %         'MarkerFaceColor' , nmap(x,1:3), ...
%         
%     plot(foodDensity(2),f2(1,x),'o', ...
%         'color', nmap(x,1:3), ...
%         'LineWidth', 2, ...
%         'MarkerFaceColor' , nmap(x,1:3), ...
%         'MarkerSize', 8)
%   	plot(foodDensity(2),f2(4,x),'o', ...
%         'color', nmap(x,1:3), ...
%         'LineWidth', 2,'MarkerSize', 8)
%     
%     plot(foodDensity(3),f3(1,x),'o', ...
%         'color', nmap(x,1:3), ...
%         'LineWidth', 2, ...
%         'MarkerFaceColor' , nmap(x,1:3), ...
%         'MarkerSize', 8)
%   	plot(foodDensity(3),f3(4,x),'o', ...
%         'color', nmap(x,1:3), ...
%         'LineWidth', 2,'MarkerSize', 8)
%     end
% % end
% 
% 
