function makepXvid(seasonal_amp, y, foodDensity, z, nnt, p_X, muPlus, nmap)

frameRate = 60;

pXvfname = sprintf('pX-envplus_%1.3f-env_samp_%1.3f-env_X_%1.3f.avi', muPlus, seasonal_amp(y), foodDensity(z));


writerObj = VideoWriter(pXvfname); % Name it.
writerObj.FrameRate = frameRate; % How many frames per second.
open(writerObj);

fid1 = figure;
figure(fid1)
hold on

    for b = 2:length(nnt)
        % muPlus(1)
        plot(nnt(b-1:b), p_X(b-1:b, 1), '-', ...
            'color', nmap(1,1:3), ...
            'LineWidth', 2)
        plot(nnt(b-1), p_X(b-1,1), 'o', ...
            'color', nmap(1,1:3), ...
            'MarkerFaceColor' , nmap(1,1:3), ...
            'MarkerSize', 5)
        % muPlus(2)
        plot(nnt(b-1:b), p_X(b-1:b, 2), '-', ...
            'color', nmap(2,1:3), ...
            'LineWidth', 2)
        plot(nnt(b-1), p_X(b-1,2), 'o', ...
            'color', nmap(2,1:3), ...
            'MarkerFaceColor' , nmap(2,1:3), ...
            'MarkerSize', 5)
        % muPlus(3)
        plot(nnt(b-1:b), p_X(b-1:b, 3), '-', ...
            'color', nmap(3,1:3), ...
            'LineWidth', 2)
        plot(nnt(b-1), p_X(b-1,3), 'o', ...
            'color', nmap(3,1:3), ...
            'MarkerFaceColor' , nmap(3,1:3), ...
            'MarkerSize', 5)
%         % muPlus(4)
        plot(nnt(b-1:b), p_X(b-1:b, 4), '-', ...
            'color', nmap(4,1:3), ...
            'LineWidth', 2) 
        plot(nnt(b-1), p_X(b-1,4), 'o', ...
            'color', nmap(4,1:3), ...
            'MarkerFaceColor' , nmap(4,1:3), ...
            'MarkerSize', 5)
        hold on
        title(strcat('+', int2str(muPlus), ' samp=', int2str(seasonal_amp(y)), ' X=', int2str(foodDensity(z))));
        setpXProperties
        frame = getframe(gcf);
        writeVideo(writerObj, frame);
    end
    hold off
    close(writerObj);
    clear pXvfname writerObj fid1
        
%         for a = 1:n_t
%             plot(nnt(1:a),p_X(1:a,1),'b', ...
%                 nnt(1:a),p_X(1:a,2),'g', ...
%                 nnt(1:a),p_X(1:a,3),'m', ...
%                 nnt(1:a),p_X(1:a,4),'r')
%             for i = 1:length(muPlus)
%                 Legend{i} = strcat('mu = ', int2str(muPlus(i)));
%             end
%             legend(Legend,'Location','eastoutside');
%             frame = getframe(gcf); % 'gcf' can handle if you zoom in to take a movie.
%             writeVideo(writerObj, frame);
%             
%         end
%         
%         hold off
%         close(writerObj); % Saves the movie.